name: "HA MCP Bridge Hybrid v2"
version: "2.0.1"
slug: "ha-mcp-bridge-v2"
description: "Hybrid MCP server with add-on + integration capabilities for Claude.ai"
url: "https://github.com/shaike1/haos-mcp/tree/main/ha-mcp-bridge"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
ports:
  3003/tcp: 3003
ports_description:
  3003/tcp: "MCP Server HTTP Port"
webui: "http://[HOST]:[PORT:3003]"
ingress: true
ingress_port: 3003
options:
  admin_password: "changeme123!"
  log_level: "info"
  external_access_method: "nabu_casa"
schema:
  admin_password: "str"
  log_level: "list(debug|info|warning|error)"
  external_access_method: "list(nabu_casa|port_forward|reverse_proxy)"
hassio_api: true
homeassistant_api: true